spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/person?useUnicode=true&characterEncoding=utf-8
    username: root
    password:

mybatis:
    mapper-locations: classpath:Mappers/*.xml
    type-aliases-package: com.me.bean
    configuration:
          cache-enabled: true
          lazy-loading-enabled: false
          aggressive-lazy-loading: true
          multiple-result-sets-enabled: true
          map-underscore-to-camel-case: true
          auto-mapping-behavior: full
          use-column-label: true
          use-generated-keys: false
          default-executor-type: simple
          default-statement-timeout: 25000